language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: E+NIZkiHUqzRWTIFsLh+mSkCiQoYa1B09j0miurtdkNhYSApa/N1n8wW4sKAQU8xKcnLuB6p8/fG7M931yPiKT9lW3kHnfa+6miPZ9kdkVchDumT+2ONxxx+knfSEz2rCUvd0E+IYjpn9k4TcqUJZgaikXIqtjFWnkLsZjc2OIhMWDK0EqNJwl3hemcWg4jrJh3FUKDWwjebVdGGoDKz76nMofsicMKmYr9a/0kxb7rixXo2IgXB2St9MfWqBGQCJav/NuAKOOtedh6gmhY0IFpicLhnMYs8Em5aJm9sXKWFFz3xQtUMMg/Pkvs7G4aZ5lfBEETHU3BhlsYUMczRppUPbVqtIq+gteHE9xtESwGBON/IQ9bAdxJyCrHlGjOqKnQ7yuByJaqLAhZD1//U2Vdw8p23KPeEsNqQj6pr62/0APbzSPR8sIQ1WQJ05XJMKEDDgmJRE2/gj+yS+aACJMXu6fVwQ0WBmrqJghNykiHmFamk0ScAMAariOG7h130Niy60u/P1RQofiVL3opk7gCS8cQCXFhCVLhf4EYANth2S575UxNSc+FGZ3RDpFuo315K+RKBdGkx9xDBakKzJ1EfkjJ4vPIbTwNppwzjCZClTIVQG+Rg/sDGTIsYvMqF7H7iKVcwGiu2N4YHzkkm8RiJDXxqQqfbjz6wmnEBkbI=
  app: quiet-meadow-32669
  on:
    repo: Btan579/jam-soon-api
