language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ELCOPKQ+hs+fxYuVNEs0qfQD1ehkZYw0tCaLSqFeTqbCet7OXy+eZip3yEWKtelhQJHvwtJH79pAo4k9xmuC0KZ5kJzWSgh6R+sLhtUXhqP7Nu8k1iudRK4oFEcMKnazhRH3EgCcYmBVOghTo6/XQTul/9/ZXsTqYgDemtn62DjY1xxJ9YyUHDuKQtEGrkFhHLqdSe90PmN2cLUm2Vx7ZvzNB7FyOxPQ4yG2eEIbLKcxBiO9xVJJtQH2TIdz4D+pkNrONmeR7rpHCiyFPd/FD/tBVjXTYNC54gG1iTJZTl2eZroK+lMyG9wdvPJBB54CqN4lukgTRJjGktiaBZRuycobvoQYcI3PdDtlQEKKT032+Jwig51RaqinY5dWRSaWM/Bj+CTYG/nCk0R7dy/JAIRXazw9ApAKKHyH462Bi9x+uErqrTNEEs2EwQ5jdtE2k//BEmZ2C/AI+T/p35UUDEEWAOCRXoVPbSjftFM0dkyxmq9CZP8HaGLDhFkrozWuHa8yJjxjgtJbdI13z+ZywXRhAgiorkvYZU66JaUkQp0eOZep/YrE/jyb4I5CbZseuubyi4BbQpoLHSRL6WCpUb14gTMzKYrDfojrfZ6X8KVGdnuCZQvjS9FM2YafATLUdL4K/gx/Am+zs56xn1r7T0iUwQGPcTMXytIn/lJGQ8E=
  app: quiet-meadow-32669
  on:
    repo: Btan579/jam-soon-api
