language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ZoJaNYSG7jBfpnuME/mfd4o+K8SKLVdoQKn4jAtbnwr8LkTr/XTw43/auFI3iT2fovsVIS5bLb6pcr1Wouuz2zy1r0wct/SVj1P0sJbO0N697rilYwuKMisCfiqVTyxZmwXQGSZu0S0hjxcQb3aW4EzI3IeHkLJdY9utOnwbx1v6j6nVwwbPEOgTspYFw4qth7kyRrldiPjS4OnVRq8rQXAImKg0qBql26PnQxGKj0/JZaSEvM+po9+lY2UH27brEg3+FUequmNqIZIxKOEazNUZROIOMY5pJBie2TFMlHWW+BRlIgH1j5QwEzrotGxakHnpWs8uMzsrUcNlY4S8cxBRC2Xca4CLj8pKSVpxondbXYlZ2sZ1wuw7T8Q4cBhvvirs5DZCCxE15ro88pczQ98wzMlioR7GlrH4RKgo7jdSZimSr42RvHvxuBdd14Ic9KM1jVXc5jIGecoC4zTz9xvnr+C/80blyHNQA/6Sku0kRnxm6B8EHjfIi8q6K9XLtlSyihJs2Ov7P79mB2KxjpC8GRsfRPBSk5wLhL2gv+lLhT98vLJiqmNLzF6VZN4JzDiKSxwswUfbjyXMlW99RfZfu0g1o1qTGw/+Fz2X8Q7babZ5g9OnrwKYne+Y+EGKHjc7gCXaNF5BrCbJkRlJo9QTGn7FLXy4/oKJ13Xh9zY=
  app: quiet-meadow-32669
  on:
    repo: Btan579/jam-soon-api
