language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: JAKzGWq1aNWCKockvzwE7bmjdArN3aWoX44TYU+8UXLdEUe23OCXx93PvAPNQEmVCPOCkROgEKnKC1kU2tv36K0Xi48BQGLsLTP/mFgMHgHDr8aZ2a4I5i8Lpfzb5wF5CH6UnxpLdieTdf/n/Jb9ffJi0lzqc+vdSsR95R7tUUoFi7tqbZjXL6D3OgfuKIoB4qVl5HeJvXq+XuoInw+Hf/zXaFWCrdIgl2rlQxpDpXGVfJY8LX8TzurLzUyagSrWbvLhwwHIOZqu7VG2dBWyB+DE2up1QVRoBmQvQIbXuy7fNtEOgSMhlvB7JLvDvAddL1W90rXrCSZ3GArBn/MWXYVCkMULABEMUiRM2l9d5hWfm6sqIWD7aP3BjR86fEePYp+UZ2KyB79QmD4QmUcKMhPmtyvr/zo6fvwWqzWr38dcHxMcOPEClKByW6m5EKdkPHv8VVIw3LUNRLKyQTpDiNNpvPupXNzu6iDMhYsfrGsvZ3bIpIE2hD0WANdoTOWqGu6ryfd9JTbe2i6CSsyWY4Tcjx91vxlseowZj2/VWtdI/X0N9qSZDqOyQTHEYOXeczFZwhSvooeiWZauV4ROdkwuj8V5D8Q/cfAhnYqQk9B/PC0xddIA+lcmoVd2qcdAwG9bTaYCt33HcWpbxbrgdwXwNP45nZcOa7Kc20Jl3yY=
  app: quiet-meadow-32669
  on:
    repo: Btan579/jam-soon-api
