language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: kQuOKswV9WmCLjrc7ZV8XOC4gyva4vEJnMEtokb4REtKvikVFe7GjgjH1xRQ2PPT5OyK374Z3gHZMCNg938nxbm+eBq8wXDdMnlR118frMV85+E39VmUVV38zt9bIZDax7zl8bzYhtQTXhFCeMmWNGVMsKIziMoSqXuTzNlGHr4DPHOA6ftseJGLFE4dCb4IlXHjKOEdKgiALbDuJDbah0oYKzU925eQffrYNN94YT/MU8822NDXsFxa2wE2wo55+oX6WnjOw5nj19M648wRcYaNSwI30WvQdcS9UybVsUgHFD4X56LQsB0FRVbNwBOjUqpiDelr57rY2wHu20EXkwhlmZU9bNL+jDsDvIwrwUInbaUUFUjwVC1pJA1iJ77k/JZypaoxXe22+6rOlW+Y/8GIDvDZhUkk1n34GdLL54y+VHdXtJCmdgm1K7UOA20JTItgnF0k9LbvoyEPf84TSEEqLpP2uf0g7pkIFOKvcaAjvaEafFsxRZY3WZBHfSTO10Gj+2W1uSJl8+OWURZ/nobm4urhW/Vxhv5kSr8YFF6Zd4LnZMktNqK9Iw/751TP/KrGEfkm6AYbwSQ2+151Hd5CfbEBMZdmiF4bnvyyEz2BQQW2h3biFSL5MlFblgysIFHN8yZCVfqAOa8OBSLdLlO3GcZjrJ3Qtoeev9envzw=
  app: quiet-meadow-32669
  on:
    repo: Btan579/jam-soon-api
